# config/services.yaml - Section Redis avec SncRedisBundle

parameters:
    redis.socket_path: '/home2/divi4480/.cpanel/redis/redis.sock'
    redis.password: '%env(REDIS_PASSWORD)%'

services:
    redis.connection:
        alias: 'snc_redis.default'
        public: true

    App\Service\MaintenanceCacheService:
        arguments:
            $redis: '@snc_redis.default'
            $logger: '@logger'
        tags:
            - { name: 'monolog.logger', channel: 'maintenance_cache' }

    maintenance.cache:
        alias: App\Service\MaintenanceCacheService
        public: true

    Redis:
        alias: 'snc_redis.default'
        public: true