# config/packages/snc_redis.yaml
snc_redis:
    clients:
        default:
            type: phpredis  # Changé de predis à phpredis
            alias: default
            # DSN corrigé pour socket Unix avec mot de passe
            dsn: 'redis://:e2a9701dead496d5a9251a4a94079d5a@/home2/divi4480/.cpanel/redis/redis.sock/0'
            logging: '%kernel.debug%'
            options:
                connection_timeout: 10.0
                read_write_timeout: 30.0
                
        cache:
            type: phpredis
            alias: cache
            dsn: 'redis://:e2a9701dead496d5a9251a4a94079d5a@/home2/divi4480/.cpanel/redis/redis.sock/1'
            logging: false
            options:
                connection_timeout: 10.0
                read_write_timeout: 30.0

# Format DSN pour socket Unix : redis://:password@/path/to/socket/database_number