# config/services.yaml - Version simplifiée sans constantes Redis

parameters:
    redis.socket_path: '/home2/divi4480/.cpanel/redis/redis.sock'
    redis.password: '%env(REDIS_PASSWORD)%'

services:
    # Service de cache maintenance avec SncRedis (simple)
    App\Service\MaintenanceCacheService:
        arguments:
            $redis: '@snc_redis.default'
            $logger: '@logger'
        tags:
            - { name: 'monolog.logger', channel: 'maintenance_cache' }

    # Alias pour compatibilité
    maintenance.cache:
        alias: App\Service\MaintenanceCacheService
        public: true

    # SUPPRESSION des services redis.connection et Redis qui causent problème
    # On utilise uniquement SncRedisBundle