# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

parameters:
    redis.socket_path: '/home2/divi4480/.cpanel/redis/redis.sock'
    redis.password: '%env(REDIS_PASSWORD)%'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Kernel.php'

    # ==================== SÉCURITÉ ====================
    
    # Enregistrement explicite de UsersAuthenticator
    App\Security\UsersAuthenticator:
        arguments:
            $urlGenerator: '@router'
        tags:
            - { name: 'security.authenticator' }

    # ==================== SERVICES DE CACHE ====================
    
    # Service de cache maintenance avec SncRedis
    App\Service\MaintenanceCacheService:
        arguments:
            $redis: '@snc_redis.default'
            $logger: '@logger'
        tags:
            - { name: 'monolog.logger', channel: 'maintenance_cache' }

    # Alias pour compatibilité
    maintenance.cache:
        alias: App\Service\MaintenanceCacheService
        public: true

    # Service de cache Kizeo
    App\Service\KizeoCacheService:
        arguments:
            $cache: '@cache.app'
            $logger: '@monolog.logger.kizeo_cache'
        tags:
            - { name: 'monolog.logger', channel: 'kizeo_cache' }

    # ==================== SERVICES PDF ET IMAGES ====================
    
    # Service de génération PDF existant
    App\Service\PdfGenerator:
        autowire: true
        autoconfigure: true

    # Service de gestion des images d'équipements
    App\Service\ImageStorageService:
        arguments:
            $projectDir: '%kernel.project_dir%'
            $logger: '@logger'
        tags:
            - { name: 'monolog.logger', channel: 'image_storage' }

    # ==================== CONTROLLERS ====================
    
    # Controller PDF des équipements avec optimisation images
    App\Controller\EquipementPdfController:
        arguments:
            $imageStorageService: '@App\Service\ImageStorageService'
            $pdfGenerator: '@App\Service\PdfGenerator'
            $httpClient: '@http_client'
            $logger: '@logger'
        tags: ['controller.service_arguments']

    # Controller de maintenance simplifié
    App\Controller\SimplifiedMaintenanceController:
        arguments:
            $imageStorageService: '@App\Service\ImageStorageService'
        tags: ['controller.service_arguments']

    # ==================== COMMANDES CONSOLE ====================
    
    # Commande de téléchargement des images
    App\Command\DownloadImagesCommand:
        arguments:
            $imageStorageService: '@App\Service\ImageStorageService'
            $logger: '@logger'
        tags:
            - { name: 'console.command' }